### ISSUE TITLE
have you considered using libvirt | libvirt ansible module?

### ISSUE THREAD

**Issue by tryauuum** [lateralblast/vamp#1]
Sorry for sudden criticism, but executing `virsh` with subprocess and parsing output feels very painful 

have you considered using this module https://docs.ansible.com/ansible/latest/collections/community/libvirt/virt_module.html ? I haven't tried it but at least they use `libvirt` python module instead of parsing virsh output.

or you can even use libvirt from your code directly

```
import libvirt


# https://libvirt.org/uri.html
connection = libvirt.open(f"qemu+ssh://10.120.0.150/system?no_tty=1&no_verify=1")
domain = connection.lookupByName('foo')

**Comment by richardatlateralblast** [comment]
Thanks for the feedback, I've looked at libvirt module previously, but as I also script KVM and VirtualBox VM creation, so I wanted something that was easily transferable back and forth between the two for me. I also found a few cases where using the XML based import approach based approached failed, or didn't give me what I wanted for more complex configurations, like those with hardware parse through. I'll close this and add some documentation regarding this and point to the alternatives.
